import Layout from '@/views/layout/index.vue'
const demoRouter={
    path:'/demo',
    component:Layout,
    redirect:'/demo/table',
    name:'demo',
    meta:{
        title:'框架教程',
    },
    children:[
        {
            path:'table',
            component:()=>import('@/views/demo/BasicTable'),
            name:'BasicTable',
            meta:{
                title:'基本表格'
            }
        },
        {
            path:'form',
            component:()=>import('@/views/demo/BasicForm'),
            name:'BasicForm',
            meta:{
                title:'基本表单'
            }
        },
        {
            path:'layout',
            component:()=>import('@/views/demo/BasicLayout'),
            name:'BasicLayout',
            meta:{
                title:'基本布局'
            }
        },
        {
            path:'vuex',
            component:()=>import('@/views/demo/VuexDemo'),
            name:'VuexDemo',
            meta:{
                title:'vuex教程'
            }
        },
        {
            path:'websocket',
            component:()=>import('@/views/demo/WebSocketDemo'),
            name:'WebSocketDemo',
            meta:{
                title:'Websocket教程'
            }
        },
        {
            path:'mockdata',
            component:()=>import('@/views/demo/MockData'),
            name:'MockData',
            meta:{
                title:'模拟ajax数据教程'
            }
        },
        {
            path:'echarts',
            component:()=>import('@/views/demo/EchartsDemo'),
            name:'echarts',
            meta:{
                title:'Ajax渲染Echarts表格'
            }
        },
        {
            path:'vuerouter',
            component:()=>import('@/views/demo/VueRouterDemo'),
            name:'vuerouter',
            meta:{
                title:'框架新增菜单与页面'
            }
        },
        {
            path:'axios',
            component:()=>import('@/views/demo/AjaxDemo'),
            name:'axios',
            meta:{
                title:'请求后台数据'
            }
        },
        {
            path:'ele',
            component:()=>import('@/views/demo/ElementUIEdit'),
            name:'ele',
            meta:{
                title:'修改ElemntUI组件样式'
            }
        },
        {
            path:'img',
            component:()=>import('@/views/demo/ImgDemo'),
            name:'img',
            meta:{
                title:'框架引入图片'
            }
        },
        {
            path:'debug',
            component:()=>import('@/views/demo/VueDebug'),
            name:'debug',
            meta:{
                title:'Vscode调试Vue'
            }
        },
        {
            path:'util',
            component:()=>import('@/views/demo/CommonUtil'),
            name:'util',
            meta:{
                title:'平台工具类使用'
            }
        },
        {
            path:'perm',
            component:()=>import('@/views/demo/PermDemo'),
            name:'perm',
            meta:{
                title:'权限指令使用'
            }
        },
        {
            path:'iframe',
            component:()=>import('@/views/demo/IFrameDemo'),
            name:'iframe',
            meta:{
                title:'iframe嵌入'
            }
        }
    ]
}
export default demoRouter
