import Layout from '@/views/layout/index.vue'
const imfRouter={
    path:'/imf',
    component:Layout,
    redirect:'/imf/app',
    name:'imf',
    meta:{
        title:'IMF',
    },
    children:[
        {
            path:'app',
            component:()=>import('@/views/imf/App'),
            name:'App',
            meta:{
                title:'应用管理'
            }
        },
        {
            path:'msg',
            component:()=>import('@/views/imf/Msg'),
            name:'Msg',
            meta:{
                title:'消息管理'
            }
        },
        {
            path:'AppService',
            component:()=>import('@/views/imf/AppService'),
            name:'AppService',
            meta:{
                title:'应用服务管理'
            }
        },
        {
            path:'type',
            component:()=>import('@/views/imf/MsgType'),
            name:'MsgType',
            meta:{
                title:'消息分类管理'
            }
        },
        {
            path:'route',
            component:()=>import('@/views/imf/MsgRoute'),
            name:'MsgRoute',
            meta:{
                title:'消息路由管理'
            }
        },
        {
            path:'service',
            component:()=>import('@/views/imf/Service'),
            name:'Service',
            meta:{
                title:'数据服务管理'
            }
        },
    ]
}
export default imfRouter
